# Generated by Django 2.0.1 on 2018-01-24 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='kind',
        ),
        migrations.AddField(
            model_name='country',
            name='tag',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Tag'),
        ),
    ]
