# Generated by Django 2.0.1 on 2018-01-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180124_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Tag'),
        ),
    ]
